import { Save } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import type { Task } from "@/lib/supabase/types";

export type TaskCourseChoice = { id: string; title: string };
export type TaskModuleChoice = { id: string; courseId: string; label: string };
export type TaskLessonChoice = { id: string; moduleId: string; label: string };
const localDeadline = (value?: string | null) => value ? new Date(value).toISOString().slice(0, 16) : "";

export function TaskForm({ action, task, courses, modules, lessons }: { action: (data: FormData) => void | Promise<void>; task?: Task; courses: TaskCourseChoice[]; modules: TaskModuleChoice[]; lessons: TaskLessonChoice[] }) {
  return <form action={action} className="space-y-5 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8">{task && <input type="hidden" name="id" value={task.id} />}<div className="space-y-2"><Label htmlFor="title">Task title</Label><Input id="title" name="title" defaultValue={task?.title} maxLength={180} required className="h-12 rounded-xl" /></div><div className="space-y-2"><Label htmlFor="description">Instructions and requirements</Label><Textarea id="description" name="description" defaultValue={task?.description} maxLength={20000} required rows={8} className="min-h-44 rounded-xl" /></div><div className="grid gap-5 sm:grid-cols-2"><Choice label="Course" name="course_id" value={task?.course_id} required options={courses.map((course) => [course.id, course.title])} /><Choice label="Module (optional)" name="module_id" value={task?.module_id} options={modules.map((module) => [module.id, module.label])} /><Choice label="Lesson (optional)" name="lesson_id" value={task?.lesson_id} options={lessons.map((lesson) => [lesson.id, lesson.label])} /><Choice label="Submission type" name="submission_type" value={task?.submission_type ?? "text"} required options={[["text", "Written response"], ["url", "URL / link"]]} /></div><div className="grid gap-5 sm:grid-cols-2"><div className="space-y-2"><Label htmlFor="points">Maximum points</Label><Input id="points" name="points" type="number" min="0" max="10000" step="1" defaultValue={task?.points ?? 10} required className="h-12 rounded-xl" /></div><div className="space-y-2"><Label htmlFor="deadline">Deadline (optional)</Label><Input id="deadline" name="deadline" type="datetime-local" defaultValue={localDeadline(task?.deadline)} className="h-12 rounded-xl" /></div></div><label className="flex cursor-pointer items-start gap-3 rounded-xl border border-slate-200 p-4"><input type="checkbox" name="resubmission_allowed" defaultChecked={task?.resubmission_allowed ?? true} className="mt-1 h-4 w-4 accent-blue-600" /><span><strong className="block">Allow revision and resubmission</strong><small className="mt-1 block text-sm text-slate-500">Students can update submitted or returned work, but not work under review or already approved.</small></span></label><Button type="submit" size="lg" className="h-12 rounded-xl bg-blue-600 px-6 font-extrabold hover:bg-blue-700"><Save className="h-5 w-5" />{task ? "Save task details" : "Create draft task"}</Button></form>;
}

function Choice({ label, name, value, options, required }: { label: string; name: string; value?: string | null; options: string[][]; required?: boolean }) { return <div className="space-y-2"><Label htmlFor={name}>{label}</Label><select id={name} name={name} defaultValue={value ?? ""} required={required} className="h-12 w-full rounded-xl border border-slate-300 bg-white px-3 outline-none focus:border-blue-500 focus:ring-4 focus:ring-blue-100"><option value="">{required ? "Select an option" : "None"}</option>{options.map(([id, text]) => <option key={id} value={id}>{text}</option>)}</select></div>; }
