import Link from "next/link";
import { BookOpen, ClipboardCheck, Users, WalletCards } from "lucide-react";
import { DashboardShell } from "@/components/dashboard-shell";
import { Card } from "@/components/ui/card";
import { requireAdmin } from "@/lib/auth/session";
const plannedModules = [[WalletCards,"Rewards","Oversee future points and reward activity"]] as const;

export const dynamic = "force-dynamic";

export default async function AdminDashboard() {
  const { profile } = await requireAdmin();
  return <DashboardShell admin eyebrow="Admin dashboard" title="Platform overview" profile={profile}><div className="rounded-2xl border border-blue-200 bg-blue-50 p-5 text-blue-950"><p className="font-extrabold">Secure admin access</p><p className="mt-1 text-sm leading-6 text-blue-800">Course, assessment, and student records are protected by server-side role checks and database policies.</p></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><Card className="p-6"><span className="grid h-11 w-11 place-items-center rounded-xl bg-blue-600 text-white"><BookOpen className="h-5 w-5"/></span><h2 className="mt-5 text-xl font-extrabold">Courses</h2><p className="mt-2 leading-7 text-slate-600">Create, edit, publish, archive, and organize modules and lessons.</p><Link href="/admin/courses" className="mt-5 inline-flex font-extrabold text-blue-700 hover:underline">Manage courses →</Link></Card><Card className="p-6"><span className="grid h-11 w-11 place-items-center rounded-xl bg-teal-600 text-white"><Users className="h-5 w-5"/></span><h2 className="mt-5 text-xl font-extrabold">Students</h2><p className="mt-2 leading-7 text-slate-600">Review student profiles and enrollment activity without exposing sensitive account controls.</p><Link href="/admin/students" className="mt-5 inline-flex font-extrabold text-blue-700 hover:underline">View students →</Link></Card><Card className="p-6"><span className="grid h-11 w-11 place-items-center rounded-xl bg-violet-600 text-white"><ClipboardCheck className="h-5 w-5"/></span><h2 className="mt-5 text-xl font-extrabold">Quizzes</h2><p className="mt-2 leading-7 text-slate-600">Create secure lesson assessments, manage questions, and control publishing.</p><Link href="/admin/quizzes" className="mt-5 inline-flex font-extrabold text-blue-700 hover:underline">Manage quizzes →</Link></Card>{plannedModules.map(([Icon,title,text])=><Card key={title} className="p-6"><span className="grid h-11 w-11 place-items-center rounded-xl bg-slate-950 text-white"><Icon className="h-5 w-5"/></span><h2 className="mt-5 text-xl font-extrabold">{title}</h2><p className="mt-2 leading-7 text-slate-600">{text}</p><span className="mt-5 inline-block rounded-full bg-slate-100 px-3 py-1 text-xs font-extrabold text-slate-500">COMING LATER</span></Card>)}</div></DashboardShell>;
}
